let imgQuizList = [
    {
        no:1,
        ans:"laptop",
        ques:"quizImages/img-1.png",
        options:[
            "mouse",
            "computer",
            "keyboard",
            "laptop"
        ]
    },
    {
        no:2,
        ans:"banana",
        ques:"quizImages/img-7.png",
        options:[
            "carrot",
            "banana",
            "mango",
            "orange"
        ]
    },
    {
        no:3,
        ans:"keyboard",
        ques:"quizImages/img-5.png",
        options:[
            "mouse",
            "piano",
            "screen",
            "keyboard"
        ]
    },
    {
        no:4,
        ans:"lion",
        ques:"quizImages/img-6.png",
        options:[
            "tiger",
            "lion",
            "cat",
            "donkey"
        ]
    },
    {
        no:5,
        ans:"cat",
        ques:"quizImages/img-8.png",
        options:[
            "zebra",
            "mouse",
            "cat",
            "dog"
        ]
    },
    {
        no:6,
        ans:"apple",
        ques:"quizImages/img-2.png",
        options:[
            "apple",
            "mango",
            "banana",
            "orange"
        ]
    },
    {
        no:7,
        ans:"mouse",
        ques:"quizImages/img-3.png",
        options:[
            "monitor",
            "cpu",
            "keyboard",
            "mouse"
        ]
    },
    {
        no:8,
        ans:"leaf",
        ques:"quizImages/img-4.png",
        options:[
            "tomato",
            "broccoli",
            "leaf",
            "corn"
        ]
    }
]